language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "nightly"

before_install:
  # download miniconda (for Python 2 or Python 3)
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  # install miniconda
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  # update conda package manager
  - conda update --yes conda

install:
  # create virtual environment
  - conda create -n testenv --yes --file requirements.txt python=$TRAVIS_PYTHON_VERSION
  # activate environment
  - source activate testenv
  # debugging info
  - echo $PATH
  - which python
  - python --version
  - conda info
  - conda list
  # install package
  - python setup.py install

script: "py.test percolate"
